services:
  - type: web
    name: opsvoice-rag-api
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt && python embed_sop.py   # <--- embed during build
    startCommand: gunicorn -b 0.0.0.0:10000 app:app                       # <--- only start API here!
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1


